### ISSUE TITLE
Score not reset on restart

### ISSUE THREAD

**Issue by jouni-kantola** [jouni-kantola/grid-snake#22]
Have to score a heart to reset score. Should always reset new game score to 0.

**Comment by Khusyasy** [comment]
Hi, can i take a look at this one?

**Comment by jouni-kantola** [comment]
Go for it, @Khusyasy!

**Comment by Khusyasy** [comment]
Okay @jouni-kantola , I'll take a look as soon as possible.

**Comment by Khusyasy** [comment]
Hey @jouni-kantola I can't seem to replicate the issue you have here, can I get more info about this issue please?

**Comment by jouni-kantola** [comment]
To repro:
1. Start a game 
2. Take 2 hearts; score is 20
3. Press Start again to reset game 
4. Displayed score is still 20 (until a new heart is taken, which displays proper score)

At step 3, the score displayed should be reset to 0. 

/ Jouni

**Comment by Khusyasy** [comment]
I'm sorry I still can't reproduce the issue. So I will not taking this issue.

**Comment by jouni-kantola** [comment]
Thanks for having a look!

**Comment by jouni-kantola** [comment]
I couldn't reproduce it with desktop browsers either. Cleared cache on my mobile, which was running an older version of Grid Snake. Problem gone.
